services:
  lms_postgres:
    image: postgres:17 # Use a specific version for stability
    container_name: lms_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # The PostgreSQL user (superuser)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # The password for the user
      POSTGRES_DB: ${POSTGRES_DB} # The default database name
      POSTGRES_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data in a named volume
    ports:
      - "5432:5432" # Map port 5432 on the host to the container
volumes:
  postgres_data: